In [28]:
!pip install numpy

In [29]:
!pip install pandas

In [30]:
!pip install scikit-learn

In [5]:
# one hot code generator
import csv
import numpy as np
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [6]:
with open("finalized_processed_dataset.csv", "r") as jammer:
    reader = list(csv.reader(jammer, delimiter=","))[1:]
    inhibition_values = list(map(lambda x : float(x[6].strip()) , reader))
    final_ans = list(map(lambda x : x[10].strip() , reader))
# reader

In [7]:
# smiles_collection = ["CC=C#C", "CC&C+C"] # this will be a list read from csv containing all smiles found
smiles_collection = final_ans
# smiles_collection
# inhibition_values

In [8]:
# smiles are strings, to add on whene elements are read from a csv file, every row would be an array and every col would \
# be a string irrespective of its type at start.

# to get all (char's/fields) possible out of smiles generated and have them as keys of agent' smiles
# since everythings a string, join those with zero spaces and put them into a set

def generateFields(smiles_collection: list) -> list:
    """
    return Type -> set
    
    args:
        smiles_collection : list -> to obtain an iterable / list of smiles
        
    objective: 
        to take unique characters of pooling all strings/smiles together and
        retrieve a list containing unique chars used, which's sorted (based on ascii vals)
    """
    return sorted(set(''.join(smiles_collection)))

# generateFields(smiles_collection)

In [9]:
def generateHotCode(smiles: str, field_generated: list) -> list:
    """
    return Type -> list
    
    args:
        smiles : str -> represents the smiles fed to function call
        field_generated : list -> collection of ordered unique chars in smiles set, used for generating onehotcodes
    
    objective:
        when a string / smiles is fed to the function it contrives a new list and assign high(1) low(0) values
        to the list index corresponding to indexes of fields generated
    """
    
    # traverse through field_generated and check whether every char exists or not -> if exist 1 else 0
    return list(map(lambda x : int(x in smiles), field_generated))

# generateHotCode("CC=#", ["#", "&", "+", "=", "C"])

In [20]:
# main block

field_generated = generateFields(smiles_collection) # field for smiles_collection is made

# loop through smiles and pass every one of it to generateHotCode then store in an array

# using array comprehension
final_sol = [generateHotCode(i, field_generated) for i in smiles_collection]
final_sol_repsntatn = [''.join(map(str,generateHotCode(i, field_generated))) for i in smiles_collection ]
final_sol_repsntatny = dict([(i,''.join(map(str,generateHotCode(i, field_generated)))) for i in smiles_collection])

final_sol_repsntatny

{'c3ccc2cc1ccccc1cc2c3': '000000111000000000000010000',
 'CCCCCCCC(=O)OCCC': '011000000001010001000000000',
 'CCCCCCCCCCCCCC(O)=O': '011000000001010001000000000',
 'COc2cc(C=CC(=O)CC(=O)C=Cc1ccc(O)c(OC)c1)ccc2O': '011000110001010001000010000',
 'N#CCc1ccccc1': '100000100000010010000010000',
 'Oc1ccc(cc1)C3CC(=O)c2c(O)cc(O)cc2O3': '011000111001010001000010000',
 'OCC5OC(Oc3cccc4C(C1OC(CO)C(O)C(O)C1O)c2cc(CO)cc(O)c2C(=O)c34)C(O)C(O)C5O': '011000111111010001000010000',
 'COc1ccc(cc1O)C5CC(=O)c4c(O)cc(OC3OC(COC2OC(C)C(O)C(O)C2O)C(O)C(O)C3O)cc4O5': '011000111111010001000010000',
 'Oc2cc(O)c1c(=O)c(O)c(oc1c2)c3ccc(O)c(O)c3': '011000111001000001000010001',
 'OCC1OC(C(O)C(O)C1O)c4c(O)c(C2OC(CO)C(O)C(O)C2O)c3oc(cc(=O)c3c4O)c5ccc(O)c(O)c5': '011000111111010001000010001',
 'Oc2cc(O)c1c(=O)cc(oc1c2)c3ccc(O)c(O)c3': '011000111001000001000010001',
 'Oc1ccc(cc1)c3cc(=O)c2c(O)cc(O)cc2o3': '011000111001000001000010001',
 'COc2cc1oc(cc(=O)c1cc2OC)c3cc(OC)c(OC)c(OC)c3': '011000111001010001000010001',
 'C

In [21]:
# writing the abv to a csv file
with open("ultra_final_dataset.csv", "w", newline="") as jammer:
    writer = csv.writer(jammer)
    writer.writerow(["One-Hot-Encoding", "Inhibition Value"])
    writer.writerows(zip(final_sol_repsntatn, inhibition_values))

In [22]:
# regression model

# data = pd.read_csv('ultra_final_dataset.csv')  # load data set
# X = data.iloc[:, 0].values.reshape(-1, 1)  # values converts it into a numpy array
# Y = data.iloc[:, 1].values.reshape(-1, 1)  # -1 means that calculate the dimension of rows, but have 1 column
X, Y = list(map(lambda x: [int(x)], final_sol_repsntatn)), list(map(lambda x: [float(x)], inhibition_values))


In [23]:

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.2, random_state=0)

In [24]:
# ------------------------------------------------------------------------------>
# Linear Regression

In [25]:
# creating the model
linear_regressor = LinearRegression()
# training the model
linear_regressor.fit(X_train, Y_train)

None

In [26]:
# predicting the test set results
Y_pred_linear = linear_regressor.predict(X_test)
Y_pred_linear

array([[0.48888375114247],
       [0.48888375114246774],
       [0.7149328487140031],
       [0.4888837262770643],
       [0.48888375114244514],
       [0.4888837488819765],
       [0.4888837488819539],
       [0.4888837488819765],
       [0.48888374887971603],
       [0.46401832280674055],
       [0.48888375114244537],
       [0.4888837488819765],
       [0.48888350022794186],
       [0.4888837488819765],
       [0.4888837262748038],
       [0.4640183454116302]], dtype=object)

In [27]:
# find R2 score a.k.a r squared score 
# for linear regression
r2_score(Y_test, Y_pred_linear)

0.10238685803533676

In [28]:
# ------------------------------------------------------------------------------>
# Decision Tree

In [31]:
decision_regressor = DecisionTreeRegressor(random_state = 0) 
decision_regressor.fit(X_train, Y_train)
None

In [32]:
Y_pred_decision = decision_regressor.predict(X_test)
Y_pred_decision

array([0.57334545, 0.57334545, 0.71246667, 0.22959286, 0.57334545,
       0.57334545, 0.57334545, 0.57334545, 0.57334545, 0.1818    ,
       0.57334545, 0.57334545, 0.45518   , 0.57334545, 0.22959286,
       0.1       ])

In [34]:
# find R2 score a.k.a r squared score 
# for decision trees
r2_score(Y_test, Y_pred_decision)

0.16029089674614305

In [35]:
# ------------------------------------------------------------------------------>
# Random Forest Regressor

In [37]:
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)
rf_regressor.fit(X_train, Y_train)

C:\Users\Arun\AppData\Local\Temp\ipykernel_21796\982323029.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_regressor.fit(X_train, Y_train)


RandomForestRegressor(random_state=42)

In [38]:
Y_pred_rf = rf_regressor.predict(X_test)
Y_pred_rf

array([0.57601221, 0.57601221, 0.71891147, 0.22991366, 0.57601221,
       0.57601221, 0.57601221, 0.57601221, 0.57601221, 0.258788  ,
       0.57601221, 0.57601221, 0.44159845, 0.57601221, 0.22991366,
       0.388718  ])

In [39]:
r2_score(Y_test, Y_pred_rf)

0.22332624035483062